name: autodeployer
on:
  push:
    branches:
      - 'main'

jobs:
  deploying:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./autodeployer
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: npm run generate -y
