name: autodeployer
on:
  push:
    branches:
      - 'main'

jobs:
  deploying:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd autodeployer
      - run: yarn install
      - run: npm run generate -y
